kind: pipeline
type: docker
name: default

steps:

- name: restore-cache
  image: meltwater/drone-cache
  pull: if-not-exists
  settings:
    backend: "filesystem"
    restore: true
    cache_key: "volume"
    archive_format: "gzip"
    mount:
      - ./.m2/repository
  volumes:
  - name: cache
    path: /tmp/cache

- name: maven-build
  image: maven:3-eclipse-temurin-8
  commands:
  - mvn verify -B -V

- name: rebuild-cache
  image: meltwater/drone-cache
  pull: if-not-exists
  settings:
    backend: "filesystem"
    rebuild: true
    cache_key: "volume"
    archive_format: "gzip"
    mount:
      - ./.m2/repository
  volumes:
  - name: cache
    path: /tmp/cache

trigger:
  branch:
  - master
  - feature/*
  event:
  - push

volumes:
  - name: cache
    host:
      path: /var/lib/cache
